### ISSUE TITLE
It has been running, and it has not ended after waiting for a long time

### ISSUE THREAD

**Issue by centerqi** [iuliaturc/detextify#16]
![image](https://user-images.githubusercontent.com/2747472/208021654-c56f848d-2805-41fd-9056-81fef887ebcb.png)

**Comment by centerqi** [comment]
![image](https://user-images.githubusercontent.com/2747472/208026927-8f2f991a-4924-462d-9a77-33762380577a.png)

output:
![octopus_detet](https://user-images.githubusercontent.com/2747472/208026985-96b5f18b-bec0-4ef6-ac74-7a4e4e792300.png)

**Comment by iuliaturc** [comment]
Could you share what text detector and in-painter you used?
And is the octopus.png image the one in the README?
