### ISSUE TITLE
A1111 extension?

### ISSUE THREAD

**Issue by Zyin055** [iuliaturc/detextify#18]
This would be nice as an Automatic1111 extension. Could add a script in the img2img tab.

**Comment by scruffynerf** [comment]
It would also be useful in training images to remove text from a pile of images before training them.

I agree, a A1111 extension would be awesome in both cases

**Comment by iuliaturc** [comment]
I would argue it doesn't make much sense as an A1111 extension. In A1111, you can manually mask the text and ask for an in-paint. The goal of this library is to run this operation on a large volume of images, without manual intervention to identify where the text is.
