### ISSUE TITLE
Don't use Numpy 1.24 as it's broken with Paddle

### ISSUE THREAD

**Issue by scruffynerf** [iuliaturc/detextify#20]
see https://github.com/PaddlePaddle/PaddleOCR/issues/8743

Requirements should be set to Numpy=1.23 for now, until they fix things.  Setting it to ^1.23 is breaking stuff, as it sees 1.24 and then fails to work.

**Comment by iuliaturc** [comment]
Thanks a lot @scruffynerf! Downgraded to Numpy=1.23.5.
