### ISSUE TITLE
Error when running pip install detextify

### ISSUE THREAD

**Issue by yasserelsaid** [iuliaturc/detextify#22]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/51494209/211670199-484a2882-5b32-4640-a078-1d25aa41f615.png">

Can you help me resolve this?

**Comment by iuliaturc** [comment]
Thanks for flagging this problem @yasserelsaid. A few questions:
- What's your OS?
- And are you using CPU or GPU?
- Could you provide the exact commands you used for installation?

**Comment by yasserelsaid** [comment]
- Mac OS Monterey on M1 Chop
- CPU, I ran `pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple` and it worked perfectly
- I then ran `pip install detextify`

`Running setup.py install for PyMuPDF ...` takes a long time (maybe 5 min)
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/51494209/211861569-41cfaa3f-bab6-408e-a86b-0d33ae0a87f2.png">

After the 5 min it shows this:
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/51494209/211862992-1ddee43c-6f60-4ce4-afad-af6d69a25d25.png">

**Comment by iuliaturc** [comment]
Closing as obsolete; we replaced the PaddleOCR library with Tesseract, since it was causing a lot of trouble at installation.
