### ISSUE TITLE
Exception: You need a GPU + CUDA to run this model locally.

### ISSUE THREAD

**Issue by jameswan** [iuliaturc/detextify#31]
Unsure why I am getting this error when there is GPU and CUDA already installed.

Traceback (most recent call last):
  File "C:\Users\James\Desktop\detextify\detext.py", line 19, in <module>
    detextifier = Detextifier(PaddleTextDetector(), LocalSDInpainter())
  File "C:\Users\James\anaconda3\envs\tf\lib\site-packages\detextify\inpainter.py", line 155, in __init__
    raise Exception("You need a GPU + CUDA to run this model locally.")
Exception: You need a GPU + CUDA to run this model locally.

(tf) C:\Users\James\Desktop\detextify>python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

**Comment by jameswan** [comment]
Solved.

In Anaconda
1. Create environment with Python **3.8**
2. Install PyTorch for GPU
3. pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple
4. pip install detextify

**Comment by rbychn** [comment]
I did all this and am still getting the same error, is there another fix?

**Comment by jameswan** [comment]
> I did all this and am still getting the same error, is there another fix?

What's your error? Did you check if torch is installed properly? That's typically the problem spot

**Comment by rbychn** [comment]
Used some details from [here](https://github.com/iuliaturc/detextify/issues/26) and fixed it. Now it's not able to find tesseract on my windows even though when I do `tesseract -v` it is able to show me the details.
